__CONFIG _XT_OSC &_WDT_OFF & _PWRTE_ON
LIST P = 16F84A
INCLUDE <P16F84A.INC>

CBLOCK 0X0C
ENDC

ORG 0
;CONFIGURACION DE PUERTOS
	BSF	STATUS,RP0

;Servo 1.
;CONFIGURACION DE RBO PARA SALIDA PWM
	BCF	TRISB,0
;CONFICURACION DE RBA0,1,2 PARA CAMBIAR POSICION
	BSF	TRISA,0
	BSF	TRISA,1
	BSF	TRISA,2


;Servo 1.
;CONFIGURACION DE RBO PARA SALIDA PWM
	BCF	TRISB,1
;CONFICURACION DE RBA0,1,2 PARA CAMBIAR POSICION
	BSF	TRISA,3
	BSF	TRISA,4
	BSF	TRISA,5

;TIMER 0 ASIGNACION DE PRESCALER DE 64
	MOVLW	B'00000101'
	MOVWF	OPTION_REG
;FIN DE CONFIGURACION
	BCF	STATUS,RP0
;INICIO DE PROGRAMA 
GOTO HOME
;**** TIEMPOS **
;** 0.5 MS
TIME_500US	EQU	D'248'
TIMEOF_500US	MOVLW	TIME_500US
				MOVWF	TMR0
				BCF		INTCON,T0IF
TIME_REB		BTFSS	INTCON,T0IF;DETECTA SI SE DESBORDO EL TEMPORIZADOR
				GOTO	TIME_REB
				RETURN
;*** 1MS ****
TIME_1MS	EQU	D'240'
TIMEOF_1MS		MOVLW	TIME_1MS
				MOVWF	TMR0
				BCF		INTCON,T0IF
TIME_REB2		BTFSS	INTCON,T0IF
				GOTO	TIME_REB2
				RETURN
;*** 2MS ****
TIME_2MS	EQU	D'225'
TIMEOF_2MS	MOVLW	TIME_2MS
			MOVWF	TMR0
			BCF		INTCON,T0IF
TIME_REB3	BTFSS	INTCON,T0IF
			GOTO	TIME_REB3
			RETURN
;*** 4MS ****
TIME_4MS	EQU	D'193'
TIMEOF_4MS	MOVLW	TIME_4MS
			MOVWF	TMR0
			BCF		INTCON,T0IF
TIME_REB4	BTFSS	INTCON,T0IF
			GOTO	TIME_REB4
			RETURN
; *** 15 MS ****
TIME_15MS	EQU D'21'
TIMEOF_15MS	MOVLW	TIME_15MS
			MOVWF	TMR0
			BCF		INTCON,T0IF
TIME_REB5	BTFSS	INTCON,T0IF
			GOTO	TIME_REB5
			RETURN
;*** 16 MS ***
TIME_16MS	EQU	D'6'
TIMEOF_16MS	MOVLW	TIME_16MS
			MOVWF	TMR0
			BCF		INTCON,T0IF
TIME_REB6	BTFSS	INTCON,T0IF
			GOTO	TIME_REB6
			RETURN
;** DEFINICION DE POSICIONES **
;CERO GRADOS
HOME
		BTFSS	PORTA,0
		GOTO	NOV;HOME_2
ZER		BSF		PORTB,0
		CALL	TIMEOF_500US
		BCF		PORTB,0
		CALL	TIMEOF_15MS
		CALL	TIMEOF_4MS
		CALL	TIMEOF_500US
		GOTO HOME2
;HOME_2	BTFSS	PORTA,1
;		GOTO	HOME
;NOVENTA GRADOS
NOV		BSF		PORTB,0
		CALL	TIMEOF_1MS
		CALL	TIMEOF_2MS
		BCF		PORTB,0
		CALL	TIMEOF_16MS
		CALL	TIMEOF_2MS
		CALL	TIMEOF_500US
		GOTO	HOME2

HOME2
			BTFSS	PORTA,3
			GOTO	NOV2;HOME_2
ZER2		BSF		PORTB,1
			CALL	TIMEOF_500US
			BCF		PORTB,1
			CALL	TIMEOF_15MS
			CALL	TIMEOF_4MS
			CALL	TIMEOF_500US
			GOTO HOME
NOV2		BSF		PORTB,1
			CALL	TIMEOF_1MS
			CALL	TIMEOF_2MS
			BCF		PORTB,1
			CALL	TIMEOF_16MS
			CALL	TIMEOF_2MS
			CALL	TIMEOF_500US
			GOTO	HOME
END